spring:
  application:
    name: Trusted One
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_APPLICATION_USER:trusted_one}
    password: ${DB_APPLICATION_PASS:trusted_one}
    driver-class-name: org.postgresql.Driver
    schema: trusted_one
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_LIQUIBASE_USER:trusted_one_liquibase}
    password: ${DB_LIQUIBASE_PASS:trusted_one_liquibase}
    default-schema: trusted_one

security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:9000}