spring:
  jackson:
    deserialization:
      accept-empty-string-as-null-object: true
  application:
    name: Trusted One
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_APPLICATION_USER:trusted_one}
    password: ${DB_APPLICATION_PASS:trusted_one}
    driver-class-name: org.postgresql.Driver
    schema: trusted_one
  jpa:
    show-sql: false
  properties:
    hibernate:
      format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_LIQUIBASE_USER:trusted_one_liquibase}
    password: ${DB_LIQUIBASE_PASS:trusted_one_liquibase}
    default-schema: trusted_one

security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:9000}
  jwt:
    secret: ${JWT_SECRET:abcdefghijlkmnopqrstuvwxyz123456}
    expiration: 3600000